name: streaming_lakehouse
version: "1.0.0"
config-version: 2

profile: streaming_lakehouse

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  streaming_lakehouse:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
